spring.application.name=transaction-service

# ===============================
# SERVER
# ===============================
server.port=8080

# ===============================
# POSTGRESQL
# ===============================
spring.datasource.url=jdbc:postgresql://localhost:55432/smartbancs
spring.datasource.username=smartbancs
spring.datasource.password=SmartBancs2026!
spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# JPA / HIBERNATE
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

# ===============================
# RABBITMQ
# ===============================
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=smartbancs
spring.rabbitmq.password=smartbancs123

# ===============================
# ACTUATOR
# ===============================
management.endpoints.web.exposure.include=health,info,metrics,prometheus
management.endpoint.health.show-details=always